### ISSUE TITLE
App keeps close

### ISSUE THREAD

**Issue by XPaimoNX** [Mahmud0808/Iconify#10]
time: 1668522048970
msg: java.lang.ClassCastException: java.lang.Boolean cannot be cast to java.lang.String
stacktrace: java.lang.ClassCastException: java.lang.Boolean cannot be cast to java.lang.String
	at android.app.SharedPreferencesImpl.getString(SharedPreferencesImpl.java:302)
	at com.drdisagree.iconify.config.PrefConfig.loadPrefSettings(PrefConfig.java:45)
	at com.drdisagree.iconify.ui.QsRowColumn.applyRowColumn(QsRowColumn.java:24)
	at com.drdisagree.iconify.services.ApplyOnBoot$2.run(ApplyOnBoot.java:66)
	at java.lang.Thread.run(Thread.java:1013)

**Comment by Mahmud0808** [comment]
Can you tell me exactly when and how it happens? So that I can reproduce the issue.

**Comment by XPaimoNX** [comment]
After i apply the option i choose it got close and then tap it again its
close again so i need to clear data it to work properly. I thinks the laat
option i choose is the status bar/ qs panel font and icon size.

**Comment by Mahmud0808** [comment]
Found the issue and fixed it. Wait for update.
