### ISSUE TITLE
[BUG] Can't run Mir Pay because of Iconify

### ISSUE THREAD

**Issue by farline99** [Mahmud0808/Iconify#132]
### Describe the bug

Mir Pay (russian GPay alternative) can't execute because of Iconify. I use Iconify only to change Monet colors. Repainter does not have this problem in this use case. Logs from logcat in additional context.

### Steps to reproduce

1. Install Iconify
2. Grant all permissions, wait..., reboot device.
3. Try to start Mir Pay app
4. You can't start app

### Expected behavior

You can use Mir Pay.

### Screenshots

![Screenshot_20230413-125510_Mir Pay](https://user-images.githubusercontent.com/100877226/231724026-08854b71-763e-40e9-b9b7-cd28f64b20d7.png)

### Device information

- Device: Xiaomi Mi 10T Pro
- OS: Arrow OS Android 12L
- App version: Latest Stable **or** latest dev. Does not matter.

### Additional context

[Mir Pay crash report]
Failed to open APK '/product/overlay/IconifyComponentAMAC.apk': I/O error

[ResourcesManager crash report]
failed to preload asset path '/product/overlay/IconifyComponentAMAC.apk'
java.io.IOException: Failed to load asset path /data/resource-cache/product@overlay@IconifyComponentAMAC.apk@idmap
	at android.content.res.ApkAssets.nativeLoad(Native Method)
	at android.content.res.ApkAssets.<init>(ApkAssets.java:295)
	at android.content.res.ApkAssets.loadOverlayFromPath(ApkAssets.java:215)
	at android.app.ResourcesManager.loadApkAssets(ResourcesManager.java:452)
	at android.app.ResourcesManager.access$000(ResourcesManager.java:72)
	at android.app.ResourcesManager$ApkAssetsSupplier.load(ResourcesManager.java:168)
	at android.app.ResourcesManager.createApkAssetsSupplierNotLocked(ResourcesManager.java:980)
	at android.app.ResourcesManager.getResources(ResourcesManager.java:1101)
	at android.app.LoadedApk.getResources(LoadedApk.java:1307)
	at android.app.ContextImpl.createAppContext(ContextImpl.java:3037)
	at android.app.ContextImpl.createAppContext(ContextImpl.java:3029)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6660)
	at android.app.ActivityThread.access$1500(ActivityThread.java:256)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2091)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7870)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:550)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

**Comment by Mahmud0808** [comment]
Try [Magisk Delta](https://github.com/HuskyDG/magisk-files/releases) and enable SuList from there. Don't forget to enable Iconify in SuList.

Edit: Looks like MirPay detects any kind of changes in overlays and refuses to work.

**Comment by farline99** [comment]
Sorry, I have quite a lot of Magisk modules and I would not like to lose them. How could Magisk-Delta help me? Mir Pay's behavior is strange)

**Comment by Mahmud0808** [comment]
Afaik repainter doesn't use any Runtime Resource Overlays, instead it uses Fabricated Overlays. That's why it doesn't have issue with Mir Pay.

But Iconify uses both RRO and Fabricated Overlays. RROs are detected by Mir Pay and that's why it's refusing to work. I don't know if there is any solution for it yet.

**Comment by farline99** [comment]
Thanks for the quick response. I will believe that you will be able to come up with something to avoid such a nuisance.

**Comment by farline99** [comment]
What else I noticed. The problem arises when you try to change the colors of the system or change icons in quick settings. With transparency in quick settings or tweaks to the status bar, it works without problems. Now I use a bunch of Repainter for colors and Iconify for some other customization.

**Comment by Mahmud0808** [comment]
Yeah if you use the options which doesn't enable any RROs, you are good to go.

**Comment by Mahmud0808** [comment]
There is a fix available now. [Mir Pay Security LSPosed Module](https://modules.lsposed.org/module/ru.bluecat.mirpaysecurity)
Credit goes to [Blue cat](https://github.com/BlueCat300)

**Comment by farline99** [comment]
@Mahmud0808, I've been using this module for about a month, but before the latest module update, Mir Pay broke down if, for example, you enabled an alternative type of notification. Now I updated the module and now everything, Mir Pay works stably under any settings. Thank you for this project! ❤️
