### ISSUE TITLE
[BUG] When I turn on Bluetooth, system UI restarts

### ISSUE THREAD

**Issue by sigako** [Mahmud0808/Iconify#182]
### Describe the bug

If I turn on Bluetooth , system ui will restart.

### Steps to reproduce

1. Go to Settings-Bluetooth
2. Click on 'Use Bluetooth'
3. See error

### Expected behavior

fix this bug

### Device information

- Device: [e.g. Sony Xperia 5 II]
- OS: [e.g. stock ROM Android version 12.0]
- App version: [v6.2.0]

**Comment by tadekdudek** [comment]
This probably only happens on Android 12, tried it on a few 13 devices and everything is fine. I don't own any 12 device, so I can't confirm this.

**Comment by Mahmud0808** [comment]
Are you using any icon pack? Does it happen in older versions?

**Comment by sigako** [comment]
> Are you using any icon pack? Does it happen in older versions?

Yes, I used icon pack. It will be fine if i don't use it. This problem also happen in older versions.

**Comment by sigako** [comment]
> Are you using any icon pack? Does it happen in older versions?

This happens only when I change the status bar icons

**Comment by Mahmud0808** [comment]
> > Are you using any icon pack? Does it happen in older versions?
> 
> This happens only when I change the status bar icons

Happens only with the first 4 icon packs? or all of them?

**Comment by sigako** [comment]
just circular,filled,oos,rounded have this bug

**Comment by Mahmud0808** [comment]
> just circular,filled,oos,rounded have this bug

Can you share crash log?

**Comment by sigako** [comment]
FATAL EXCEPTION: main
Process: com.android.systemui, PID: 16443
android.content.res.Resources$NotFoundException: Drawable android:drawable/ic_bluetooth_transient_animation with resource ID #0x1080335
Caused by: android.content.res.Resources$NotFoundException: File res/drawable/ic_bluetooth_transient_animation.xml from drawable resource ID #0x1080335
	at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:874)
	at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:668)
	at android.content.res.Resources.loadDrawable(Resources.java:993)
	at android.content.res.Resources.getDrawableForDensity(Resources.java:983)
	at android.content.res.XResources.getDrawableForDensity(Unknown Source:78)
	at android.content.res.Resources.getDrawable(Resources.java:922)
	at android.content.res.XResources.getDrawable(Unknown Source:78)
	at android.content.Context.getDrawable(Context.java:757)
	at com.android.systemui.qs.tileimpl.QSTileImpl$ResourceIcon.getInvisibleDrawable(QSTileImpl.java:754)
	at com.android.systemui.qs.tileimpl.QSIconViewImpl.updateIcon(QSIconViewImpl.java:116)
	at com.android.systemui.qs.tileimpl.QSIconViewImpl.setIcon(QSIconViewImpl.java:172)
	at com.android.systemui.qs.tileimpl.QSIconViewImpl.setIcon(QSIconViewImpl.java:105)
	at com.android.systemui.qs.tileimpl.QSTileViewImpl.handleStateChanged(QSTileViewImpl.kt:353)
	at com.android.systemui.qs.tileimpl.QSTileViewImpl$onStateChanged$1.run(QSTileViewImpl.kt:259)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:346)
	at android.os.Looper.loop(Looper.java:475)
	at android.app.ActivityThread.main(ActivityThread.java:7889)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1009)
Caused by: java.lang.ClassCastException: android.graphics.drawable.BitmapDrawable cannot be cast to android.graphics.drawable.VectorDrawable
	at android.graphics.drawable.AnimatedVectorDrawable.inflate(AnimatedVectorDrawable.java:541)
	at android.graphics.drawable.DrawableInflater.inflateFromXmlForDensity(DrawableInflater.java:145)
	at android.graphics.drawable.Drawable.createFromXmlInnerForDensity(Drawable.java:1399)
	at android.graphics.drawable.Drawable.createFromXmlForDensity(Drawable.java:1358)
	at android.content.res.ResourcesImpl.loadXmlDrawable(ResourcesImpl.java:906)
	at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:860)
	... 21 more

**Comment by Mahmud0808** [comment]
Try this version https://github.com/Mahmud0808/Iconify/actions/runs/5346085629

Let me know if the issue is still there or not.

**Comment by sigako** [comment]
no issue now , thank u
