### ISSUE TITLE
App crashes on cr droid android 13

### ISSUE THREAD

**Issue by Illmind** [Mahmud0808/Iconify#27]
Crash log : 
time: 1669465716757
msg: java.lang.ClassCastException: java.lang.Boolean cannot be cast to java.lang.String
stacktrace: java.lang.ClassCastException: java.lang.Boolean cannot be cast to java.lang.String
	at android.app.SharedPreferencesImpl.getString(SharedPreferencesImpl.java:302)
	at com.drdisagree.iconify.config.PrefConfig.loadPrefSettings(PrefConfig.java:45)
	at com.drdisagree.iconify.ui.QsRowColumn.applyRowColumn(QsRowColumn.java:24)
	at com.drdisagree.iconify.services.ApplyOnBoot$2.run(ApplyOnBoot.java:83)
	at java.lang.Thread.run(Thread.java:1012)
[GitHub](https://github.com/lus/pasty)

**Comment by Mahmud0808** [comment]
Does it happen while trying to change row and columns?

**Comment by Illmind** [comment]
Fixed after clearing data and cache.

**Comment by Mahmud0808** [comment]
Found the issue and fixed it. Wait for update.
