### ISSUE TITLE
[BUG] error: Failed to create/flash module zip

### ISSUE THREAD

**Issue by Tobapuww** [Mahmud0808/Iconify#374]
### Describe the bug

Create an overlay an error occurred.

Log:
Iconify bug report 10 12月 2023 19:58:03
version: 6.5.1 (15)
build.brand: Xiaomi
build.device: raphael
build.display: SQ3A.220705.004
build.fingerprint: Xiaomi/derp_raphael/raphael:12/SQ3A.220705.004/1660244459:userdebug/release-keys
build.hardware: qcom
build.id: SQ3A.220705.004
build.manufacturer: Xiaomi
build.model: Redmi K20 Pro
build.product: derp_raphael
build.type: userdebug
version.codename: REL
version.release: 12
version.sdk_int: 32
iconify.version_name: 6.5.1
iconify.version_code: 15

error: Failed to create/flash module zip

Onboarding:
java.lang.Exception: Incomplete Magisk install

	at com.drdisagree.iconify.utils.ModuleUtil.flashModule(ModuleUtil.java:166)
	at com.drdisagree.iconify.ui.activities.Onboarding$StartInstallationProcess.doInBackground(Onboarding.java:559)
	at com.drdisagree.iconify.ui.activities.Onboarding$StartInstallationProcess.doInBackground(Onboarding.java:362)
	at com.drdisagree.iconify.utils.TaskExecutor.runInBackground(TaskExecutor.java:87)
	at com.drdisagree.iconify.utils.TaskExecutor.lambda$execute$2(TaskExecutor.java:56)
	at com.drdisagree.iconify.utils.TaskExecutor.$r8$lambda$NdWNjfpyB_XPjBvyKYj42yO6Bgo(TaskExecutor.java:0)
	at com.drdisagree.iconify.utils.TaskExecutor$$ExternalSyntheticLambda0.run(R8$$SyntheticClass:0)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:1013)

### Steps to reproduce

Start create an overlay.

### Expected behavior

Normal use

### Device information

Iconify bug report 10 12月 2023 19:58:03
version: 6.5.1 (15)
build.brand: Xiaomi
build.device: raphael
build.display: SQ3A.220705.004
build.fingerprint: Xiaomi/derp_raphael/raphael:12/SQ3A.220705.004/1660244459:userdebug/release-keys
build.hardware: qcom
build.id: SQ3A.220705.004
build.manufacturer: Xiaomi
build.model: Redmi K20 Pro
build.product: derp_raphael
build.type: userdebug
version.codename: REL
version.release: 12
version.sdk_int: 32
iconify.version_name: 6.5.1
iconify.version_code: 15

**Comment by Tobapuww** [comment]
The bug has been resolved because of an incomplete installation of magisk on my device. Sorry for the inconvenience to the developers.
