### ISSUE TITLE
[BUG] error: Failed to create/flash module zip

### ISSUE THREAD

**Issue by FGHNBB** [Mahmud0808/Iconify#406]
### Describe the bug

I met this error while creating the overlay modules.

Here's the LOG:
```
Iconify bug report 22 January 2024 13:55:14
version: 6.6.0 (16)
build.brand: OnePlus
build.device: OnePlus5T
build.display: lineage_dumpling-userdebug 13 TQ3A.230901.001 4b09456263
build.fingerprint: OnePlus/OnePlus5T/OnePlus5T:10/QKQ1.191014.012/2010292059:user/release-keys
build.hardware: qcom
build.id: TQ3A.230901.001
build.manufacturer: OnePlus
build.model: ONEPLUS A5010
build.product: OnePlus5T
build.type: userdebug
version.codename: REL
version.release: 13
version.sdk_int: 33
iconify.version_name: 6.6.0
iconify.version_code: 16

error: Failed to create/flash module zip

Onboarding:
net.lingala.zip4j.exception.ZipException: folder does not exist
	at net.lingala.zip4j.ZipFile.addFolder(ZipFile.java:351)
	at com.drdisagree.iconify.utils.ModuleUtil.createModule(ModuleUtil.java:142)
	at com.drdisagree.iconify.ui.activities.Onboarding$StartInstallationProcess.doInBackground(Onboarding.java:565)
	at com.drdisagree.iconify.ui.activities.Onboarding$StartInstallationProcess.doInBackground(Onboarding.java:381)
	at com.drdisagree.iconify.utils.extension.TaskExecutor.runInBackground(TaskExecutor.java:87)
	at com.drdisagree.iconify.utils.extension.TaskExecutor.lambda$execute$2(TaskExecutor.java:56)
	at com.drdisagree.iconify.utils.extension.TaskExecutor.$r8$lambda$mlSKxSA6QxliO5Aq0bUDeWtkzpA(TaskExecutor.java:0)
	at com.drdisagree.iconify.utils.extension.TaskExecutor$$ExternalSyntheticLambda0.run(R8$$SyntheticClass:0)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)

```

### Steps to reproduce

Start create an overlay,using magisk mode.

### Expected behavior

No errors.

### Screenshots

![Screenshot_20240122-141419_Trebuchet](https://github.com/Mahmud0808/Iconify/assets/94230492/5b88da75-18f5-486e-ac9a-9c754d112429)
It just stuck here.

### Device information

- Device: [Oneplus 5T dumpling]
- OS: [LineageOS 20 with Android 13]
- App version: [v6.6.0]
- Magisk/KernelSU: [Magisk Stable 26.4(26400)]

### Additional context

Latest crash report.
[iconify_logcat_22-01-24_13_55_14.txt](https://github.com/Mahmud0808/Iconify/files/14005995/iconify_logcat_22-01-24_13_55_14.txt)

**Comment by HiFIi** [comment]
This project is dead

**Comment by Mahmud0808** [comment]
Looks like storage access permission related issue.

**Comment by FGHNBB** [comment]
> Looks like storage access permission related issue.

thanks a lot,but it fixed itself,i dont know how to describe it.Seems it needs /system r/w and the module works.
