### ISSUE TITLE
[BUG] SystemUI crash for keyguard

### ISSUE THREAD

**Issue by Tenun-negi** [Mahmud0808/Iconify#42]
### Describe the bug

Sometimes when i turn on screen, the system ui crash.

### Steps to reproduce

Maybe custom lockscreen clock?

### Expected behavior

Systemui crash

### Device information

- Device: Sony Xperia XZ3
- OS: Lineage OS 20
- App version: 5.0 dev #263

### Additional context

Crash log
[01-28 16:09:54.699 20890:20890 I/LSPosed-Bridge]
Crash unexpectedly: java.lang.IllegalStateException: Slice content://0@com.android.systemui.keyguard/main not pinned
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3019)
	at android.os.Parcel.createException(Parcel.java:2995)
	at android.os.Parcel.readException(Parcel.java:2978)
	at android.os.Parcel.readException(Parcel.java:2920)
	at android.app.slice.ISliceManager$Stub$Proxy.getPinnedSpecs(ISliceManager.java:385)
	at android.app.slice.SliceManager.getPinnedSpecs(SliceManager.java:194)
	at androidx.slice.builders.TemplateSliceBuilder.<init>(TemplateSliceBuilder.java:30)
	at androidx.slice.builders.ListBuilder.<init>(ListBuilder.java:0)
	at com.android.systemui.keyguard.KeyguardSliceProvider.onBindSlice(KeyguardSliceProvider.java:14)
	at com.android.keyguard.KeyguardStatusViewController.dozeTimeTick(KeyguardStatusViewController.java:32)
	at com.android.systemui.statusbar.phone.CentralSurfacesImpl$12.onScreenTurningOn(CentralSurfacesImpl.java:13)
	at com.android.systemui.keyguard.KeyguardLifecyclesDispatcher$1.handleMessage(KeyguardLifecyclesDispatcher.java:353)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7872)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.slice.SliceManagerService.getPinnedSlice(SliceManagerService.java:362)
	at com.android.server.slice.SliceManagerService.getPinnedSpecs(SliceManagerService.java:209)
	at android.app.slice.ISliceManager$Stub.onTransact(ISliceManager.java:203)
	at android.os.Binder.execTransactInternal(Binder.java:1285)
	at android.os.Binder.execTransact(Binder.java:1244)

[01-28 16:09:54.699 20890:20890 E/AndroidRuntime]
FATAL EXCEPTION: main
Process: com.android.systemui, PID: 20890
java.lang.IllegalStateException: Slice content://0@com.android.systemui.keyguard/main not pinned
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3019)
	at android.os.Parcel.createException(Parcel.java:2995)
	at android.os.Parcel.readException(Parcel.java:2978)
	at android.os.Parcel.readException(Parcel.java:2920)
	at android.app.slice.ISliceManager$Stub$Proxy.getPinnedSpecs(ISliceManager.java:385)
	at android.app.slice.SliceManager.getPinnedSpecs(SliceManager.java:194)
	at androidx.slice.builders.TemplateSliceBuilder.<init>(TemplateSliceBuilder.java:30)
	at androidx.slice.builders.ListBuilder.<init>(ListBuilder.java:0)
	at com.android.systemui.keyguard.KeyguardSliceProvider.onBindSlice(KeyguardSliceProvider.java:14)
	at com.android.keyguard.KeyguardStatusViewController.dozeTimeTick(KeyguardStatusViewController.java:32)
	at com.android.systemui.statusbar.phone.CentralSurfacesImpl$12.onScreenTurningOn(CentralSurfacesImpl.java:13)
	at com.android.systemui.keyguard.KeyguardLifecyclesDispatcher$1.handleMessage(KeyguardLifecyclesDispatcher.java:353)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7872)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.slice.SliceManagerService.getPinnedSlice(SliceManagerService.java:362)
	at com.android.server.slice.SliceManagerService.getPinnedSpecs(SliceManagerService.java:209)
	at android.app.slice.ISliceManager$Stub.onTransact(ISliceManager.java:203)
	at android.os.Binder.execTransactInternal(Binder.java:1285)
	at android.os.Binder.execTransact(Binder.java:1244)

**Comment by Mahmud0808** [comment]
Which clock style? all of them?

Edit: Fixed in latest build.
