### ISSUE TITLE
NullPointerException on all overlays when installing them

### ISSUE THREAD

**Issue by gabriel20xx** [Mahmud0808/Iconify#657]
### Describe the bug

When doing the initial configuration it throws errors:

[Stack Trace]:
java.lang.RuntimeException: Unable to instantiate application android.app.Application package IconifyComponentWIFI4.overlay: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.AssetManager android.content.res.Resources.getAssets()' on a null object reference
	at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1474)
	at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1399)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7368)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2379)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8601)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:583)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:863)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.AssetManager android.content.res.Resources.getAssets()' on a null object reference
	at android.app.LoadedApk.getAssets(LoadedApk.java:1357)
	at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1452)
	... 11 more

### Steps to reproduce

1. Install app
2. Do initial configuration 

### Expected behavior

It should not throw any errors

### Device information

- Device: Poco F3
- OS: crDroid 10.8 (Android 14)
- App version: v6.9.0
- Magisk/KernelSU: KernelSU

[Device Brand]: POCO
[Device Model]: M2012K11AG
[Display]: AP2A.240905.003
[Android Version]: 14
[Android API Level]: 34
[System Locale]: en_GB
[Process ID]: 5810
[User ID]: 0
[CPU ABI]: none
[Package Name]: IconifyComponentWIFI4.overlay
[Version Name]: v6.9.0
[Version Code]: 0
[Target SDK]: 34
[Min SDK]: 31
[Error Type]: JVM
[Crash Time]: 2024-10-24T00:52:27.190

**Comment by Mahmud0808** [comment]
Overlays do not have any application to instantiate and that's totally normal. Overlays are not like normal apps, it only includes some resources for theming purposes. You can ignore these logs.

**Comment by gabriel20xx** [comment]
Isn't it better to suppress these errors then instead of letting them happen?

**Comment by Mahmud0808** [comment]
These errors are most probably thrown by aapt2 (Android Asset Packaging Tool), which is from [AAGaming00/aapt2](https://github.com/AAGaming00/aapt2). I don't know how to build these tools from source so I can't suppress these errors either.

**Comment by termonaitor2004** [comment]
> These errors are most probably thrown by aapt2 (Android Asset Packaging Tool), which is from [AAGaming00/aapt2](https://github.com/AAGaming00/aapt2). I don't know how to build these tools from source so I can't suppress these errors either.

I know a little cmake I can look into this
