### ISSUE TITLE
[BUG] [A16-A15*] Hide QS on LS

### ISSUE THREAD

**Issue by SpacePirates6** [Mahmud0808/Iconify#687]
### Describe the bug

Hide QS on LS not functioning as intended on latest builds of android
effects A16 and some versions including stable of A15
QQS hides properly but QS Does not. the pulldown thats normally blank still contains qs content

### Steps to reproduce

1. Go to Iconify
2. Click on hide qs on ls toggle
3. Scroll down on ls

### Expected behavior

For QS to be unaccessible on LS

### Screenshots

Screenshots would not help explain the issue as it appears as if the toggle is inactive minus the QQS being missing

### Device information

- Device: P8P
- OS: Aosp A16 and some of A15
- App version: see log however tested with debug build and stable
- Magisk/KernelSU: 28.0

### Additional context

[verbose_2024-11-24T05_57_16.841063.log]

https://github.com/user-attachments/files/17895261/verbose_2024-11-24T05_57_16.841063.log

I am running other modules however I have explicitly attempted to get this to function with iconify and lsposed being the only ones to no avail.

**Comment by SpacePirates6** [comment]
https://github.com/user-attachments/files/17895261/verbose_2024-11-
24T05_57_16.841063.log

**Comment by SpacePirates6** [comment]
https://github.com/user-attachments/files/17895261/verbose_2024-11-24T05_57_16.841063.log

**Comment by SpacePirates6** [comment]
[ 2024-11-24T05:57:29.482    10252:  2349:  2349 E/LSPosed-Bridge  ] java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.ViewGroup$LayoutParams android.view.View.getLayoutParams()' on a null object reference
	at com.drdisagree.iconify.xposed.modules.Miscellaneous$hideLockscreenLockIcon$1.handleLayoutInflated(SourceFile:693)
	at NnYUrMEJDAb.R.i.KlZnEQ.callbacks.XC_LayoutInflated.call(Unknown Source:6)
	at NnYUrMEJDAb.R.i.KlZnEQ.callbacks.XCallback.callAll(Unknown Source:26)
	at QZMA.SgDhERJ.NHMqJKLqoR.ources$2.afterHookedMethod(Unknown Source:68)
	at NnYUrMEJDAb.R.i.KlZnEQ.XposedBridge$LegacyApiSupport.handleAfter(Unknown Source:33)
	at org.lsposed.lspd.impl.LSPosedBridge$NativeHooker.callback(Unknown Source:279)
	at LSPHooker_.parseInclude(Unknown Source:20)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1007)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:972)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:570)
	at java.lang.reflect.Method.invoke(Native Method)
	at jf.AcnOryj.br.S.bn.EsUVWruIsC.HookBridge.invokeOriginalMethod(Native Method)
	at org.lsposed.lspd.impl.LSPosedBridge$NativeHooker.callback(Unknown Source:187)
	at LSPHooker_.inflate(Unknown Source:21)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:462)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:413)
	at com.google.android.systemui.dagger.DaggerSysUIGoogleGlobalRootComponent$SysUIGoogleSysUIComponentImpl$SwitchingProvider.get1$1(go/retraceme ecb9ed001b8bfa7f471f1065cb03e0556388770834177583a7ef7d0cb834a669:1454)
	at com.google.android.systemui.dagger.DaggerSysUIGoogleGlobalRootComponent$SysUIGoogleSysUIComponentImpl$SwitchingProvider.get(go/retraceme ecb9ed001b8bfa7f471f1065cb03e0556388770834177583a7ef7d0cb834a669:4655)
	at dagger.internal.DoubleCheck.get(go/retraceme ecb9ed001b8bfa7f471f1065cb03e0556388770834177583a7ef7d0cb834a669:14)
	at dagger.internal.DelegateFactory.get(go/retraceme ecb9ed001b8bfa7f471f1065cb03e0556388770834177583a7ef7d0cb834a669:5)
	at com.google.android.systemui.dagger.DaggerSysUIGoogleGlobalRootComponent$SysUIGoogleSysUIComponentImpl$SwitchingProvider.get1$1(go/retraceme ecb9ed001b8bfa7f471f1065cb03e0556388770834177583a7ef7d0cb834a669:1473)
	at com.google.android.systemui.dagger.DaggerSysUIGoogleGlobalRootComponent$SysUIGoogleSysUIComponentImpl$SwitchingProvider.get(go/retraceme ecb9ed001b8bfa7f471f1065cb03e0556388770834177583a7ef7d0cb834a669:4655)
	at dagger.internal.DoubleCheck.get(go/retraceme ecb9ed001b8bfa7f471f1065cb03e0556388770834177583a7ef7d0cb834a669:14)
	at dagger.internal.DelegateFactory.get(go/retraceme ecb9ed001b8bfa7f471f1065cb03e0556388770834177583a7ef7d0cb834a669:5)
	at com.google.android.systemui.dagger.DaggerSysUIGoogleGlobalRootComponent$SysUIGoogleSysUIComponentImpl$SwitchingProvider.get4(go/retraceme ecb9ed001b8bfa7f471f1065cb03e0556388770834177583a7ef7d0cb834a669:705)
	at com.google.android.systemui.dagger.DaggerSysUIGoogleGlobalRootComponent$SysUIGoogleSysUIComponentImpl$SwitchingProvider.get(go/retraceme ecb9ed001b8bfa7f471f1065cb03e0556388770834177583a7ef7d0cb834a669:4640)
	at dagger.internal.DoubleCheck.get(go/retraceme ecb9ed001b8bfa7f471f1065cb03e0556388770834177583a7ef7d0cb834a669:14)
	at com.google.android.systemui.dagger.DaggerSysUIGoogleGlobalRootComponent$SysUIGoogleSysUIComponentImpl$SwitchingProvider.get5(go/retraceme ecb9ed001b8bfa7f471f1065cb03e0556388770834177583a7ef7d0cb834a669:4494)
	at com.google.android.systemui.dagger.DaggerSysUIGoogleGlobalRootComponent$SysUIGoogleSysUIComponentImpl$SwitchingProvider.get(go/retraceme ecb9ed001b8bfa7f471f1065cb03e0556388770834177583a7ef7d0cb834a669:4635)
	at dagger.internal.DoubleCheck.get(go/retraceme ecb9ed001b8bfa7f471f1065cb03e0556388770834177583a7ef7d0cb834a669:14)
	at dagger.internal.DelegateFactory.get(go/retraceme ecb9ed001b8bfa7f471f1065cb03e0556388770834177583a7ef7d0cb834a669:5)
[ 2024-11-24T05:57:29.482    10252:  2349:  2349 E/LSPosed-Bridge  ] 	at com.google.android.systemui.dagger.DaggerSysUIGoogleGlobalRootComponent$SysUIGoogleSysUIComponentImpl$SwitchingProvider.get7(go/retraceme ecb9ed001b8bfa7f471f1065cb03e0556388770834177583a7ef7d0cb834a669:771)
	at com.google.android.systemui.dagger.DaggerSysUIGoogleGlobalRootComponent$SysUIGoogleSysUIComponentImpl$SwitchingProvider.get(go/retraceme ecb9ed001b8bfa7f471f1065cb03e0556388770834177583a7ef7d0cb834a669:4625)
	at dagger.internal.DoubleCheck.get(go/retraceme ecb9ed001b8bfa7f471f1065cb03e0556388770834177583a7ef7d0cb834a669:14)
	at com.android.systemui.accessibility.SystemActions.registerOrUnregisterDismissNotificationShadeAction(go/retraceme ecb9ed001b8bfa7f471f1065cb03e0556388770834177583a7ef7d0cb834a669:6)
	at com.android.systemui.accessibility.SystemActions.registerActions(go/retraceme ecb9ed001b8bfa7f471f1065cb03e0556388770834177583a7ef7d0cb834a669:293)
	at com.android.systemui.accessibility.SystemActions.start(go/retraceme ecb9ed001b8bfa7f471f1065cb03e0556388770834177583a7ef7d0cb834a669:131)
	at com.android.systemui.SystemUIApplication.startStartable(go/retraceme ecb9ed001b8bfa7f471f1065cb03e0556388770834177583a7ef7d0cb834a669:26)
	at com.android.systemui.SystemUIApplication$$ExternalSyntheticLambda0.run(go/retraceme ecb9ed001b8bfa7f471f1065cb03e0556388770834177583a7ef7d0cb834a669:56)
	at com.android.systemui.SystemUIApplication.timeInitialization(go/retraceme ecb9ed001b8bfa7f471f1065cb03e0556388770834177583a7ef7d0cb834a669:28)
	at com.android.systemui.SystemUIApplication.startServicesIfNeeded(go/retraceme ecb9ed001b8bfa7f471f1065cb03e0556388770834177583a7ef7d0cb834a669:206)
	at com.android.systemui.SystemUIApplication.startSystemUserServicesIfNeeded(go/retraceme ecb9ed001b8bfa7f471f1065cb03e0556388770834177583a7ef7d0cb834a669:74)
	at com.android.systemui.SystemUIService.onCreate(go/retraceme ecb9ed001b8bfa7f471f1065cb03e0556388770834177583a7ef7d0cb834a669:10)
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:5086)
	at android.app.ActivityThread.-$$Nest$mhandleCreateService(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2512)
	at android.os.Handler.dispatchMessage(Handler.java:109)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8828)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:591)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:871)

**Comment by Mahmud0808** [comment]
~~There is no support for android 15 and 16 yet unfortunately. Last released version was for android 14.~~

~~Edit: Unfortunately it's not possible anymore.~~

Found alternative way.
